@startuml Includes
!include .\\Circulo.puml
!include .\\Mundo.puml
!include .\\Objeto.puml
!include .\\Poligono.puml
!include .\\Ponto.puml
!include .\\Program.puml
!include .\\Retangulo.puml
!include .\\SegReta.puml
!include .\\SplineBezier.puml
!include .\\SrPalito.puml
@enduml
