@startuml Objeto
class Objeto {
    + Rotulo : char <<get>>
    + PrimitivaTamanho : float <<get>> <<set>>
    + PontosListaTamanho : int <<get>>
    + Bbox() : BBox
    + Objeto(_paiRef:Objeto, _rotulo:char, objetoFilho:Objeto)
    + ObjetoAtualizar() : void
    + ObjetoMatrizGlobal(matrizGlobalPai:Transformacao4D) : Transformacao4D
    + Desenhar(matrizGrafo:Transformacao4D, objetoSelecionado:Objeto) : void
    + FilhoAdicionar(filho:Objeto) : void
    + PontosId(id:int) : Ponto4D
    + PontosAdicionar(pto:Ponto4D) : void
    + PontosAlterar(pto:Ponto4D, posicao:int) : void
    + PontosApagar() : void
    + MatrizGlobalInversa(mousePto:Ponto4D) : Ponto4D
    + GrafocenaBusca(_rotulo:char) : Objeto
    + GrafocenaAtualizar(lista:Dictionary<char, Objeto>) : Dictionary<char, Objeto>
    + GrafocenaImprimir(idt:string) : void
    + OnUnload() : void
}
Objeto --> "PrimitivaTipo" PrimitiveType
Objeto --> "ShaderObjeto" Shader
@enduml
