@startuml SrPalito
class SrPalito {
    + SrPalito(_paiRef:Objeto, rotulo:char)
    + MoverEsquerda() : void
    + MoverDireita() : void
    + DiminuirRaio() : void
    + AumentarRaio() : void
    + DiminuirAngulo() : void
    + AumentarAngulo() : void
}
Objeto <|-- SrPalito
@enduml
